serial:
  autoconnect: true
  baudrate: 115200
  port: /dev/ttyUSB0
  timeout: {}
plugins:
  cura:
    cura_engine: /usr/bin/CuraEngine
    debug_logging: false
    default_profile: null
  pluginmanager:
    pip: /usr/bin/pip-sudo
  softwareupdate:
    _config_version: 6
    checks:
      octoprint:
        checkout_folder: null
        prerelease: false
        prerelease_channel: null
    notify_users: false
webcam:
  bitrate: 15000k
  ffmpeg: /usr/bin/ffmpeg
  ffmpegThreads: 4
  snapshot: http://localhost/webcam/?action=snapshot
  stream: http://localhost/webcam/?action=stream
  timelapse:
    fps: 25
    options:
      capturePostRoll: false
      interval: 20
    postRoll: 1
    type: timed
server:
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  commands:
    serverRestartCommand: sudo systemctl restart octoprint
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
system:
  actions: []
